const text = [
  `Danish macaroon apple pie croissant bonbon croissant carrot cake brownie icing. Cotton candy cupcake fruitcake marshmallow apple pie croissant. Pastry pudding cake toffee jelly-o lollipop chocolate cake pastry. Marshmallow gingerbread jujubes sesame snaps icing apple pie cake marshmallow powder. Biscuit gummies marzipan tart ice cream. Topping macaroon halvah cake lemon drops. Muffin toffee powder pastry sesame snaps liquorice wafer jujubes tiramisu. Bonbon toffee candy tart candy canes sweet roll. Jujubes cotton candy gingerbread biscuit cupcake icing pie. Bonbon bear claw icing toffee marzipan gummies. Candy bonbon danish chocolate marshmallow powder bear claw liquorice. Shortbread sesame snaps powder sweet roll cookie marshmallow. Marzipan croissant lollipop sweet marzipan sweet roll powder gummi bears tiramisu.
  `,
  `Tootsie roll sugar plum croissant jujubes macaroon bonbon sweet biscuit. Bonbon dragée oat cake pastry cake chupa chups jelly jelly. Pastry toffee bonbon cookie bonbon candy canes gingerbread. Macaroon jelly tart gingerbread lemon drops shortbread. Tart wafer dragée jelly beans chocolate cake oat cake toffee soufflé icing. Pastry shortbread bear claw donut lemon drops oat cake cheesecake sesame snaps. Cake carrot cake cookie icing lemon drops lollipop macaroon toffee. Halvah halvah lollipop cookie candy canes cake gingerbread cake. Cake lemon drops cake donut brownie tiramisu bear claw cheesecake gummi bears. Cheesecake apple pie gummies liquorice croissant croissant. Cheesecake cookie candy candy icing. Pudding sweet gingerbread wafer lollipop candy canes lollipop topping.`,
  `
  Chocolate bar donut oat cake cupcake cookie. Chocolate tiramisu gingerbread sweet croissant toffee muffin bear claw. Jujubes halvah lemon drops gummies marzipan soufflé sesame snaps powder. Pudding candy canes cookie apple pie marshmallow lollipop. Sweet roll shortbread jujubes biscuit toffee dragée jelly. Jujubes shortbread topping sweet carrot cake cake lollipop jelly-o tart. Danish topping candy chocolate cake bear claw pudding. Donut chocolate cake wafer topping ice cream carrot cake chupa chups dessert. Tootsie roll cotton candy muffin lemon drops marshmallow. Gummi bears chocolate cake liquorice chupa chups toffee candy canes cotton candy apple pie. Chocolate cake gummies cookie jelly jujubes. Chocolate tootsie roll sweet roll cotton candy soufflé donut. Shortbread sugar plum icing marzipan sweet roll bear claw dragée. Topping brownie dragée muffin jelly cupcake powder jelly beans gingerbread.
  `,
  `ragée candy canes cupcake carrot cake cupcake sesame snaps. Danish dragée gummi bears oat cake icing bear claw marzipan candy canes. Candy canes sesame snaps gummies caramels chocolate bar. Cotton candy pastry cookie dragée lemon drops candy dragée dragée powder. Muffin bonbon toffee gummi bears brownie chocolate bar. Donut cookie cheesecake cotton candy jujubes. Chupa chups lollipop chocolate cake lemon drops macaroon bonbon. Gummies oat cake pie jelly pastry pastry tootsie roll macaroon. Biscuit jelly caramels fruitcake tiramisu icing cake cupcake sesame snaps. Bear claw chocolate bar liquorice sweet sweet roll chocolate cake wafer cake. Lollipop tart dessert gummies ice cream apple pie marshmallow bear claw liquorice. Tootsie roll fruitcake jelly beans toffee topping candy canes. Cake powder biscuit gummies carrot cake tiramisu. Topping dragée chocolate cake topping gingerbread cupcake donut.`,
  `
  Jelly-o apple pie jelly-o fruitcake tart danish brownie halvah. Powder gummi bears danish carrot cake topping biscuit. Wafer gummi bears wafer cake jujubes. Lemon drops liquorice lollipop tootsie roll tiramisu. Bonbon candy canes chupa chups lollipop caramels lollipop. Jelly gingerbread powder toffee cotton candy. Sweet roll marzipan shortbread dragée jelly. Lollipop tart topping tootsie roll donut cheesecake chocolate. Dragée topping croissant gingerbread carrot cake powder cake gingerbread icing. Sweet topping brownie caramels jelly-o. Jelly-o brownie cookie marshmallow pudding pudding candy brownie sesame snaps. Jelly-o macaroon cookie halvah muffin chocolate bar chocolate bar. Dessert muffin chocolate bar gingerbread cheesecake gummies tart bear claw. Sweet jelly beans lollipop topping chupa chups candy.
  `,
];
export default text;
